### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'toUpperCase')TypeError: Cannot read properties of undefined (reading 'toUpperCase')    at https://tauri.localhost/assets/main-0cf169f0.js:69:4725    at Array.map (<anonymous>)    at yr (https://tauri.localhost/assets/main-0cf169f0.js:69:4710)    at Object.provideCodeActions (https://tauri.localhost/assets/main-0cf169f0.js:70:392)Error: Cannot read properties of undefined (reading 'toUpperCase')TypeError: Cannot read properties of undefined (reading 'toUpperCase')    at https://tauri.localhost/assets/main-0cf169f0.js:69:4725    at Array.map (<anonymous>)    at yr (https://tauri.localhost/assets/main-0cf169f0.js:69:4710)    at Object.provideCodeActions (https://tauri.localhost/assets/main-0cf169f0.js:70:392)    at https://tauri.localhost/assets/editor.main-f745e835.js:4:53133

### ISSUE THREAD

**Issue by Eisenmochi** [bridge-core/editor#1092]
**Summary**

**To Reproduce**

4. Observe result

**Observed behavior**
A clear and concise description of what happened
**Expected behavior**

**Screenshots / File Attachments**
If applicable, add screenshots to help explain your problem or upload files to help us reproduce the bug.

**Platform (please complete the following information):**

-   OS: [e.g. Windows 10]
-   App Version: [e.g. 0.13.3]

**Additional context**

**Comment by outercloudstudio** [comment]
Please fill out the requested information.
