### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'toUpperCase')TypeError: Cannot read properties of undefined (reading 'toUpperCase')    at https://tauri.localhost/assets/main-e0f7e5ee.js:69:4725    at Array.map (<anonymous>)    at yr (https://tauri.localhost/assets/main-e0f7e5ee.js:69:4710)    at Object.provideCodeActions (https://tauri.localhost/assets/main-e0f7e5ee.js:70:392)Error: Cannot read properties of undefined (reading 'toUpperCase')TypeError: Cannot read properties of undefined (reading 'toUpperCase')    at https://tauri.localhost/assets/main-e0f7e5ee.js:69:4725    at Array.map (<anonymous>)    at yr (https://tauri.localhost/assets/main-e0f7e5ee.js:69:4710)    at Object.provideCodeActions (https://tauri.localhost/assets/main-e0f7e5ee.js:70:392)    at https://tauri.localhost/assets/editor.main-3a70c1ee.js:4:53133

### ISSUE THREAD

**Issue by TranNgoQuocThai** [bridge-core/editor#1161]
**Summary**
This error appeared several times when I was working with the en_US.lang file

**To Reproduce**

When I work with the en_US.lang file, sometimes this bug message will appear.

**Observed behavior**
It doesn't affect the working process at all, but I still want to report it.

**Platform (please complete the following information):**

Windows 11

**Additional context**
I want it to not appear anymore.

**Comment by outercloudstudio** [comment]
Thank you for reporting 👍
