### ISSUE TITLE
Error: DataCloneError: Failed to execute 'put' on 'IDBObjectStore': (i,s)=>e.then(r=>s(r.transaction(t,i).objectStore(t))) could not be cloned.Error: DataCloneError: Failed to execute 'put' on 'IDBObjectStore': (i,s)=>e.then(r=>s(r.transaction(t,i).objectStore(t))) could not be cloned.    at window.onunhandledrejection (https://tauri.localhost/assets/main-edc510ec.js:28:2506)

### ISSUE THREAD

**Issue by Litbolt123** [bridge-core/editor#1184]
**Summary**
This error comes up when I try and link the Vanilla Pack that I downloaded from the link in Bridge (https://bedrock.dev/packs). I downloaded 1.12.30.22-preview from the GitHub. 
**To Reproduce**
Drag and drop the 'resource_pack' or 'behavior_pack' into Bridge to reproduce the error. 

**Observed behavior**
This error comes up.  "Error: DataCloneError: Failed to execute 'put' on 'IDBObjectStore': (i,s)=>e.then(r=>s(r.transaction(t,i).objectStore(t))) could not be cloned.Error: DataCloneError: Failed to execute 'put' on 'IDBObjectStore': (i,s)=>e.then(r=>s(r.transaction(t,i).objectStore(t))) could not be cloned.    at window.onunhandledrejection (https://tauri.localhost/assets/main-edc510ec.js:28:2506)" 
**Expected behavior**
The packs are linked to Bridge.

-   OS: Windows 11
-   App Version: v2.7.33

**Comment by Litbolt123** [comment]
I updated the plugin and fixed the issue.
