### ISSUE TITLE
Illegal value for lineNumber error

### ISSUE THREAD

**Issue by Chikorita-Lover** [bridge-core/editor#248]
**Summary**
Seemingly randomly, bridge. will produce an error saying there was an illegal value for lineNumber. This happens commonly when deleting a large amount of content from a file while editing it. The exact error is written below.
```
Illegal value for lineNumber

Error: Illegal value for lineNumber
    at IP.getLineContent (https://editor.bridge-core.app/assets/vendor.5369cb71.js:16:646533)
    at os (https://editor.bridge-core.app/assets/main.48555c7a.js:1:84364)
    at https://editor.bridge-core.app/assets/main.48555c7a.js:1:88601
    at Sd.fire (https://editor.bridge-core.app/assets/vendor.5369cb71.js:16:99253)
    at https://editor.bridge-core.app/assets/vendor.5369cb71.js:16:1115340
    at https://editor.bridge-core.app/assets/vendor.5369cb71.js:16:639464
    at Sd.fire (https://editor.bridge-core.app/assets/vendor.5369cb71.js:16:99253)
    at $P.endDeferredEmit (https://editor.bridge-core.app/assets/vendor.5369cb71.js:16:685365)
    at IP.pushEditOperations (https://editor.bridge-core.app/assets/vendor.5369cb71.js:16:652783)
    at Function._innerExecuteCommands (https://editor.bridge-core.app/assets/vendor.5369cb71.js:16:1016233) (,Error: Illegal value for lineNumber,at IP.getLineContent (https://editor.bridge-core.app/assets/vendor.5369cb71.js:16:646533),at os (https://editor.bridge-core.app/assets/main.48555c7a.js:1:84364),at https://editor.bridge-core.app/assets/main.48555c7a.js:1:88601,at Sd.fire (https://editor.bridge-core.app/assets/vendor.5369cb71.js:16:99253),at https://editor.bridge-core.app/assets/vendor.5369cb71.js:16:1115340,at https://editor.bridge-core.app/assets/vendor.5369cb71.js:16:639464,at Sd.fire (https://editor.bridge-core.app/assets/vendor.5369cb71.js:16:99253),at $P.endDeferredEmit (https://editor.bridge-core.app/assets/vendor.5369cb71.js:16:685365),at IP.pushEditOperations (https://editor.bridge-core.app/assets/vendor.5369cb71.js:16:652783),at Function._innerExecuteCommands (https://editor.bridge-core.app/assets/vendor.5369cb71.js:16:1016233),at https://editor.bridge-core.app/assets/vendor.5369cb71.js:16:89138)
```

**Platform (please complete the following information):**
 - OS: Windows 10
 - App Version: 2.1.5

**Comment by solvedDev** [comment]
This has already been fixed on the v2.2 dev builds :)
